Feature api connect
Kevin-Shen-and-Cipher/course-forum-frontend pull request #17
Opened 2023-04-30 15:58 UTC by ian901204

2023-05-01 01:48 UTC, Kevin-MoonNight commented on src/components/Admin/PostsDataTable.vue
> +watch(
改成computed

2023-05-01 01:49 UTC, Kevin-MoonNight commented on src/components/Admin/TagsDataTable.vue
> +        console.log(editTag.value);
log要刪除

2023-05-01 01:59 UTC, Kevin-MoonNight commented on src/components/Admin/TagsDataTable.vue
> +        await router.push(import.meta.env.VITE_APP_ERROR_ROUTER);
error通常都會讓它跳出[alert](https://vuetifyjs.com/en/components/alerts/)

2023-05-01 02:01 UTC, Kevin-MoonNight commented on src/components/Admin/TagsDataTable.vue
> +watch(
改成computed

2023-05-01 02:02 UTC, Kevin-MoonNight commented on src/components/Admin/TagsDataTable.vue
> +        if (tagName !== '' && !dessert.name.includes(tagName)) {
`tagName !== ''`可以直接改成 `if(tagName && !dessert.name.includes(tagName)`

2023-05-01 02:16 UTC, Kevin-MoonNight commented on src/components/Login.vue
> +    localStorage.setItem('apartment', response.data.apartment);
改成用[pinia](https://pinia.vuejs.org/)並用[persist plugin](https://github.com/prazdevs/pinia-plugin-persistedstate)

2023-05-01 02:18 UTC, Kevin-MoonNight commented on src/components/TopBar.vue
> +const apartment = localStorage.getItem('apartment');
改成pinia

2023-05-01 02:18 UTC, Kevin-MoonNight commented on src/components/TopBar.vue
> +function logout() {
改成pinia

2023-05-01 02:19 UTC, Kevin-MoonNight commented on src/components/posts/SelectTags.vue
> +const tagsname = ref([]);
tagNames

2023-05-01 02:22 UTC, Kevin-MoonNight commented on src/views/AddPostView.vue
> +const rating = ref(0);
改成score

2023-05-01 02:24 UTC, Kevin-MoonNight commented on src/views/AddPostView.vue
post相關的可以直接宣告一個post的object 
```
post = reactive({
  title:'',
  content:'',
  score:0,
  tags:[],
})
```

2023-05-01 02:30 UTC, Kevin-MoonNight commented on src/components/posts/SelectTags.vue
combobox有個property是 [item-value](https://vuetifyjs.com/en/api/v-combobox/#props-item-value) 它可以讓你選擇的item自動去取你給他的值 例如 `item-value="id"` 這樣子如果你選擇那個tag它會去找那個object然後取它的id，這樣子你就不用特別去寫transfor了

2023-05-01 02:35 UTC, Kevin-MoonNight commented on src/views/HomeView.vue
> +        if (searchString !== '' && !post.title.includes(searchString)) {
searchString可以改成!searchString

2023-05-01 02:35 UTC, Kevin-MoonNight commented on src/views/HomeView.vue
> +        if (selectData.length > 0 && !selectData.includes(post.create_by)) {
>0可以不用加

2023-05-01 02:35 UTC, Kevin-MoonNight commented on src/views/HomeView.vue
> +        if (tagData.length > 0 && !post.tags.some((tag) => tagData.includes(tag.name))) {
同上

2023-05-01 02:37 UTC, Kevin-MoonNight requested changes
API部分建議不要寫在component裡面，拆出去成一個檔案處理，然後身分資訊放在Pinia上

2023-05-03 12:05 UTC, Kevin-MoonNight commented on src/views/AdminPostsView.vue
> +const buttonDisabled = ref(true);
可以寫成`computed(()=>selectedData.value.length === 0)`

2023-05-10 01:42 UTC, Kevin-MoonNight commented on src/components/Admin/PostsDataTable.vue
> +        @update:modelValue="$emit('update:selectedData', selected)"
如果有寫v-model這個元件裡面應該會自動更新selected吧?

2023-05-10 01:43 UTC, Kevin-MoonNight commented on src/components/Admin/PostsDataTable.vue
> +                @click="postsStore.verifySelectedPass([item.raw.id])"
要寫成`()=> postsStore.vertifySelectedPass([item.raw.id])`這樣子

2023-05-10 01:43 UTC, Kevin-MoonNight commented on src/components/Admin/PostsDataTable.vue
> +            <v-btn variant="text" color="red" @click="postsStore.deletePosts([item.raw.id])">
同上

2023-05-10 01:46 UTC, Kevin-MoonNight commented on src/components/Admin/TagsDataTable.vue
> +        @update:modelValue="$emit('update:selectedData', selected)"
同上

2023-05-10 01:47 UTC, Kevin-MoonNight commented on src/components/Home/Filter.vue
> +                        @change="$emit('update:select', selectedApartment)"
同上

2023-05-10 01:47 UTC, Kevin-MoonNight commented on src/components/Home/Filter.vue
> +                        @change="$emit('update:select', selectedApartment)"
同上

2023-05-10 01:48 UTC, Kevin-MoonNight commented on src/components/Home/Filter.vue
> +            @update:modelValue="$emit('update:tag', chips)"
同上

2023-05-10 01:49 UTC, Kevin-MoonNight commented on src/components/Home/Filter.vue
> +tagsStore.fetchTags();
這種初始化動作要放在onMounted或onBeforeMount

2023-05-10 01:52 UTC, Kevin-MoonNight commented on src/components/TopBar.vue
> +if (authStore.token != null){
這個動作要放在onMounted或onBeforeMount

2023-05-10 01:52 UTC, Kevin-MoonNight commented on src/components/posts/SelectTags.vue
> +        @update:modelValue="$emit('update:modelValue', chips)"
同上

2023-05-10 01:57 UTC, Kevin-MoonNight commented on src/router/router.js
token傳給你的時候正常來講會給expireIn時間，用個去判斷有沒有token過期就好，然後beforeEnter可以改成全域的，不用一項項寫，詳細去查docs，可以在每個route裡面加上meta data `meta :{ requiredAuth: true}` 類似這樣，就可以判斷該rotue需不需要驗證

2023-05-10 01:58 UTC, Kevin-MoonNight commented on src/store/Tags.js
> +                      Authorization: 'Bearer ' +  useAuthStore().token
useAuthStore不要直接寫在這，拿個變數去存他，放在store旁邊

2023-05-10 01:59 UTC, Kevin-MoonNight commented on src/store/auth.js
> +          //const response = await axios.post(import.meta.env.VITE_APP_API_URL + '/login', data);
忘記改

2023-05-10 02:01 UTC, Kevin-MoonNight commented on src/store/posts.js
> +            useAlertStore().callAlert(error.message, 'error');
要拿變數接store

2023-05-10 02:02 UTC, Kevin-MoonNight commented on src/views/AddPostView.vue
> +const showDate = date.getFullYear() + '-' + (date.getMonth() + 1) + '-' + date.getDate();
要寫成ref喔

2023-05-10 02:02 UTC, Kevin-MoonNight commented on src/views/AddPostView.vue
>  const date = new Date();
同下

2023-05-10 02:02 UTC, Kevin-MoonNight commented on src/views/AddPostView.vue
>  const label = '設定標籤';
同下

2023-05-10 02:03 UTC, Kevin-MoonNight commented on src/views/AdminPostsView.vue
> +postsStore.fetchPosts();
要寫在onBeforeMount

2023-05-10 02:04 UTC, Kevin-MoonNight commented on src/views/AdminTagsView.vue
> +tagsStore.fetchTags();
同上

2023-05-10 02:07 UTC, Kevin-MoonNight commented on src/views/AdminTagsView.vue
> +defineEmits(['update:selectedData', 'closeDialog']);
如果是外面的元件要取得內部元件的資料變化你要寫成
```
const data = computed({
    get:()=>{
        return props.modelValue
    },
    set:(value)=>{
        emit('update:modelValue',value);
    }
})
```
這樣子在外面的元件就能夠透過v-model來自動取得內部元件的數值變化

2023-05-10 02:09 UTC, Kevin-MoonNight commented on src/views/HomeView.vue
> +postsStore.fetchPosts();
同上

2023-05-10 02:12 UTC, Kevin-MoonNight requested changes
主要是token的問題，以及程式碼執行撰寫方式

2023-05-11 07:45 UTC, ian901204 commented on src/components/Admin/PostsDataTable.vue
> +        @update:modelValue="$emit('update:selectedData', selected)"
這個是父原件更新 我看是要這樣寫他才會讓父原件也跟著更新

2023-05-11 07:45 UTC, ian901204 commented on src/components/Admin/TagsDataTable.vue
> +        @update:modelValue="$emit('update:selectedData', selected)"
同上

2023-05-11 07:45 UTC, ian901204 commented on src/components/Home/Filter.vue
> +                        @change="$emit('update:select', selectedApartment)"
同上

2023-05-11 07:45 UTC, ian901204 commented on src/components/Home/Filter.vue
> +                        @change="$emit('update:select', selectedApartment)"
同上 都是為了給父元件更新

2023-05-11 07:46 UTC, ian901204 commented on src/components/Home/Filter.vue
> +            @update:modelValue="$emit('update:tag', chips)"
同上

2023-05-22 16:20 UTC, Kevin-MoonNight approved these changes

2023-05-22 16:20 UTC, merged